### ISSUE TITLE
 no matches for kind "CNFConfiguration" in version "pantheon.tech/v1"

### ISSUE THREAD

**Issue by Vaishu2211** [PANTHEONtech/cnf-examples#6]
While running webserver.yaml to deploy and start a simple VPP-based webserver with NSM-Agent-VPP as control-plane, I am receiving error: unable to recognize "webserver.yaml": no matches for kind "CNFConfiguration" in version "pantheon.tech/v1". 

I am trying to onboard CNF on the google cloud platform (GCP) using GKE cluster. 
kubectl version: Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T1
3:41:02Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.13-gke.401", GitCommit:"eb94c181eea5290e9da1238db02cfef263542f5f", GitTreeState:"clean", BuildDate:"20
20-09-09T00:57:35Z", GoVersion:"go1.13.9b4", Compiler:"gc", Platform:"linux/amd64"}

**Comment by Vaishu2211** [comment]
It resolved. There was some issue related to vcpus. I have upgraded CPU's quota and it worked fine.

**Comment by mmiklus** [comment]
great, thanks for your feedback !
